#include <stdio.h>
#include <stdlib.h>
#include <sys/wait.h>
#include <unistd.h>
#include <string.h>
#include <time.h>

#define AmountRandomNumber 4

int main(int argc, char const *argv[])
{
    //Declare arrays of identificators and result
    int identificators[AmountRandomNumber], results[AmountRandomNumber];

    //Initialize an id
    int i = 0;

    //Loop to create all childs
    for (int i = 0; i < AmountRandomNumber && id == 0; i++)
    {
        //Fork and store returned value at place i in the array
        identificators[i] = fork();

        //Check if process is a child
        if (identificators[i] == 0)
        {
            id = i + 1;
        }

        // Error
        else if (identificators[i] < 0)
        {
            printf("There was an error generating the process.");

            //Stop the loop
            id = -1;

            //Return an error
            return 1;
        }
        //If process is the parent, just let him loop. 
    }

    //Child
    if (id != 0)
    {
        //initialize random number
        int number = 0;

        //Random numbers are the same if created from the same process because they have the same seed
        //So using time and pid of child to change the seed used is useful to get an actual random number.
        srand(time(NULL) * getpid());

        //Get number
        number = rand();

        //Display child infos.
        printf("I'm a child.\n My pid is: %d.\n I generated this number: %d.\n", getpid(), number);

        return number;
    }

    //Parent
    else 
    {
        //Loop until results are all stored.
        for (int k = 0; k < AmountRandomNumber; k++)
        {
            //Wait the result of each kid and store it
            identificators[k] = wait(&results[k]);
            results[k] = WEXITSTATUS(results[k]);
        }

        //Display parent's pid.
        printf("I'm the father. My pid is %d.\n", getpid());

        //Loop to display numbers generated by childs and pid of which child generated which number.
        for (int l = 0; l < AmountRandomNumber; l++)
        {
            printf("Child with pid - %d - generated the number - %d -.\n", identificators[l], results[l]);
        }
    }

    return 0;
}
